# -*- coding: utf-8 -*-
"""Custom_Key_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QU81mQc0VA4ZdzP8CEUVLy2up9mkp8dZ
"""

d = [6, 8, 4, 30, 18, 23]
print(sorted(d, key = abs))

data = [[3, 6, 8], [10, 4, 9], [4, 12,26], [23, 6, 11]]

def avg(data):
  return sum(data) / len(data)

print(sorted(data, key = avg))